sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v
  - docker-compose build

script:
  - docker-compose run --rm tests

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

