version: "2"
services:

  app:
    build: .
    image: keboola/kbc-project-backup
    tty: true
    stdin_open: true
    environment:
      - KBC_TOKEN
      - KBC_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - AWS_S3_PATH
    command: sh -c 'php /home/kbc-project-backup/tests/createConfig.php && php /home/kbc-project-backup/src/run.php --data=/home/kbc-project-backup/tests/data'

  tests:
    image: keboola/kbc-project-backup
    command: /home/kbc-project-backup/tests.sh
    volumes:
      - ./:/home/kbc-project-backup
    environment:
      - KBC_TOKEN
      - KBC_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - AWS_S3_PATH
