version: "2"
services:
  app:
    build: .
    image: keboola/kbc-project-backup
    tty: true
    stdin_open: true
    volumes:
      - ./:/home
    environment:
      - KBC_TOKEN
      - KBC_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - AWS_S3_PATH
    command: sh -c 'php /home/tests/createConfig.php && php /home/src/run.php --data=/home/tests/data'
  tests:
    image: keboola/kbc-project-backup
    command: echo "test" && /home/tests.sh
    volumes:
      - ./:/home
    environment:
      - KBC_TOKEN
      - KBC_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - AWS_S3_PATH
