version: "2"
services:
  php:
    build: .
    image: keboola/kbc-project-backup
    tty: true
    stdin_open: true
    volumes:
      - ./:/home
    environment:
      - KBC_TOKEN
      - KBC_URL
  tests:
    image: keboola/kbc-project-backup
    command: sh -c '/home/tests.sh'
    volumes:
      - ./:/home
    environment:
      - KBC_TOKEN
      - KBC_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - AWS_S3_PATH
