version: "2"

services:
  app: &app
    build: .
    image: keboola/kbc-project-backup
    environment:
      - KBC_TOKEN
      - KBC_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - AWS_S3_PATH

  dev:
    <<: *app
    volumes:
      - ./data:/data
      - ./:/code
